CREATE TABLE IF NOT EXISTS `category` (
    `id` VARCHAR(32) NOT NULL COMMENT '分类ID',
    `cate_name` VARCHAR(100) NOT NULL COMMENT '分类名称',
    `blog_num` INT DEFAULT 0 COMMENT '博客数量',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cate_name` (`cate_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文章分类表';